const types = {
  INITIALIZE_NEW_GAME: 'INITIALIZE_NEW_GAME',
  USER_LOGIN: 'USER_LOGIN',
  START_QUESTION_MODAL: 'START_QUESTION_MODAL',
  GET_QUESTION: 'GET_QUESTION',
  SEND_ANSWER: 'SEND_ANSWER',
  START_NEW_GAME: 'START_NEW_GAME',
  MARK_GAME_AS_FINISHED: 'MARK_GAME_AS_FINISHED',
  LOGOUT: 'LOGOUT',
  SET_IS_PLAYING_TRUE: 'SET_IS_PLAYING_TRUE',
  SET_IS_PLAYING_FALSE: 'SET_IS_PLAYING_FALSE'
}

export default types
